# Generated by Django 4.2.7 on 2023-12-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
    ]
