# Generated by Django 4.2.7 on 2023-12-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_componenteelectronico_proveedor_delete_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='codigo_proveedor',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
